export const QUESTIONS = [
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: Ela encontrou um emprego.", opcoes: ["um", "emprego", "encontrou"], resposta: "emprego"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: O sofá é pequeno.", opcoes: ["é", "pequeno", "sofá"], resposta: "sofá"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: A sala é grande.", opcoes: ["sala", "grande", "A"], resposta: "sala"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: O pássaro come todas as frutas.", opcoes: ["come/O", "pássaro/frutas", "as/todas"], resposta: "pássaro/frutas"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: A árvore é bonita.", opcoes: ["árvore", "é", "bonita"], resposta: "árvore"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: A menina é feia.", opcoes: ["feia", "A", "menina"], resposta: "menina"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: Que filme ruim!", opcoes: ["ruim", "filme", "Que"], resposta: "filme"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: Os óculos quebraram.", opcoes: ["quebraram","os", "óculos"], resposta: "óculos"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: Ela mora em outro país.", opcoes: ["país", "ela", "em"], resposta: "país"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: Maria viajou ontem.", opcoes: ["viajou", "Maria", "ontem"], resposta: "Maria"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: Helena mora no Canadá.", opcoes: ["mora/no", "Helena/Canadá", "Canadá/mora"], resposta: "Helena/Canadá"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: Ana é inteligente!", opcoes: ["é", "inteligente", "Ana"], resposta: "Ana"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: O Brasil é lindo!", opcoes: ["lindo", "Brasil", "é"], resposta: "Brasil"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: Ele gosta de comer doces.", opcoes: ["doces", "Ele", "gosta"], resposta: "doces"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: Miguel é bom no vôlei.", opcoes: ["bom/é", "no/vôlei", "Miguel/vôlei"], resposta: "Miguel/vôlei"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: Júlia sempre faz novos amigos.", opcoes: ["Júlia/sempre", "amigos/faz", "amigos/Júlia"], resposta: "amigos/Júlia"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: O casaco é feio.", opcoes: ["casaco", "feio", "é"], resposta: "casaco"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: Eles estão trabalhando em um jogo.", opcoes: ["estão", "Eles", "jogo"], resposta: "jogo"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: Carla gosta de ler.", opcoes: ["gosta", "Carla", "ler"], resposta: "Carla"},
  {pergunta: "Leia a oração abaixo e tente encontrar o(s) substantivo(s) que estão nela: Célia é muito paciente.", opcoes: ["paciente", "Célia", "muito"], resposta: "Célia"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: Ela trabalhou muito.", opcoes: ["trabalhou", "muito", "ela"], resposta: "trabalhou"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: João morou em outra cidade.", opcoes: ["João", "outra", "morou"], resposta: "morou"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: Júlia sempre brinca sozinha.", opcoes: ["sozinha", "sempre", "brinca"], resposta: "brinca"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: Eles trabalham no campo.", opcoes: ["trabalham", "campo", "no"], resposta: "trabalham"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: A minha irmã fala inglês.", opcoes: ["minha", "fala", "inglês"], resposta: "fala"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: Miguel joga vôlei.", opcoes: ["joga", "Miguel", "vôlei"], resposta: "joga"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: Vocês gostam de ler ou não?", opcoes: ["vocês/ler", "gostam/ler", "não/ou"], resposta: "gostam/ler"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: Seu José vende pipoca na praça.", opcoes: ["vende", "praça", "pipoca"], resposta: "vende"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: As torcidas gritam nos jogos.", opcoes: ["nos", "torcidas", "gritam"], resposta: "gritam"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: Não como comida japonesa...", opcoes: ["como", "japonesa", "Não"], resposta: "como"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: Você gosta de comida mexicana?", opcoes: ["mexicana", "comida", "gosta"], resposta: "gosta"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: Em janeiro começa a estação chuvosa.", opcoes: ["janeiro", "começa", "chuvosa"], resposta: "começa"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: Ninguém faz comida como minha mãe.", opcoes: ["Ninguém", "mãe", "faz"], resposta: "faz"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: Algumas pessoas sentem mais frio que outras.", opcoes: ["pessoas", "Algumas", "sentem"], resposta: "sentem"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: Eduardo malha toda tarde.", opcoes: ["malha", "tarde", "Eduardo"], resposta: "malha"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: Eu e meu irmão dividimos tudo!", opcoes: ["meu", "dividimos", "irmão"], resposta: "dividimos"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: Ele adoeceu essa semana.", opcoes: ["semana", "essa", "adoeceu"], resposta: "adoeceu"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: Amo nadar na praia com meus amigos!", opcoes: ["amo/nadar", "praia/amigos", "na/com"], resposta: "amo/nadar"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: Você ganhou um prêmio no sorteio!", opcoes: ["Você", "prêmio", "ganhou"], resposta: "ganhou"},
  {pergunta: "Encontre qual é o verbo presente na oração a seguir: Joana é professora.", opcoes: ["é", "professora", "Joana"], resposta: "é"},
  {pergunta: "Quanto é 19x20?", opcoes: ["370", "380", "385"], resposta: 380},
  {pergunta: "Quanto é 11x18?", opcoes: ["198", "200", "199"], resposta: "198"},
  {pergunta: "Quanto é 19x19?", opcoes: ["360", "362", "361"], resposta: "361"},
  {pergunta: "Quanto é 13x18?", opcoes: ["235", "230", "234"], resposta: "234"},
  {pergunta: "Quanto é 16x19?", opcoes: ["300", "305", "304"], resposta: "304"},
  {pergunta: "Quanto é 12x10?", opcoes: ["110", "120", "115"], resposta: "120"},
  {pergunta: "Quanto é 96x5?", opcoes: ["480", "470", "485"], resposta: "480"},
  {pergunta: "Quanto é 48x2?", opcoes: ["96", "90", "95"], resposta: "96"},
  {pergunta: "Quanto é 12x5?", opcoes: ["65", "70", "60"], resposta: "60"},
  {pergunta: "Quanto é 76x3?", opcoes: ["230", "228", "227"], resposta: "228"},
  // {pergunta: "Quanto é 29x5?", opcoes: [150, 140, 145], resposta: 145},
  // {pergunta: "Quanto é 92x7?", opcoes: [700, 644, 640], resposta: 644},
  // {pergunta: "Quanto é 30x9?", opcoes: [270, 275, 260], resposta: 270},
  // {pergunta: "Quanto é 87x8?", opcoes: [695, 696, 700], resposta: 696},
  // {pergunta: "Quanto é 27x2?", opcoes: [55, 54, 57], resposta: 54},
  // {pergunta: "Quanto é 33x4?", opcoes: [130, 132, 134], resposta: 132},
  // {pergunta: "Quanto é 45x9?", opcoes: [400, 404, 405], resposta: 405},
  // {pergunta: "Quanto é 29x8?", opcoes: [230, 232, 233], resposta: 232},
  // {pergunta: "Quanto é 77x8?", opcoes: [620, 617, 616], resposta: 616},
  // {pergunta: "Quanto é 47x2?", opcoes: [95, 99, 96], resposta: 94},
  // {pergunta: "Quanto é 28÷7?", opcoes: [5, 3, 4], resposta: 4},
  // {pergunta: "Quanto é 55÷5?", opcoes: [11, 13, 12], resposta: 11},
  // {pergunta: "Quanto é 42÷2?!", opcoes: [21, 20, 18], resposta: 21},
  // {pergunta: "Quanto é 52÷4?", opcoes: [15, 13, 16], resposta: 13},
  // {pergunta: "Quanto é 85÷5?", opcoes: [15, 18, 17], resposta: 17},
  // {pergunta: "Quanto é 54÷3?", opcoes: [20, 15, 18], resposta: 18},
  // {pergunta: "Quanto é 76÷4?", opcoes: [19, 17, 21], resposta: 19},
  // {pergunta: "Quanto é 24÷4?", opcoes: [9, 4, 6], resposta: 6},
  // {pergunta: "Quanto é 22÷11?", opcoes: [3, 5, 2], resposta: 2},
  // {pergunta: "Quanto é 84÷14?", opcoes: [5, 6, 9], resposta: 6},
  // {pergunta: "Quanto é 52÷13?", opcoes: [3, 4, 2], resposta: 4},
  // {pergunta: "Quanto é 54÷6?", opcoes: [9, 8, 7], resposta: 9},
  // {pergunta: "Quanto é 170÷17?", opcoes: [11, 9, 10], resposta: 10},
  // {pergunta: "Quanto é 32÷16?", opcoes: [3, 2, 4], resposta: 2},
  // {pergunta: "Quanto é 266÷14?", opcoes: [17, 19, 20], resposta: 19},
  // {pergunta: "Quanto é 40÷4?", opcoes: [5, 10, 11], resposta: 10},
  // {pergunta: "Quanto é 18÷6?", opcoes: [7, 3, 5], resposta: 3},
  // {pergunta: "Quanto é 15÷3?", opcoes: [5, 10, 4], resposta: 5},
  // {pergunta: "Quanto é 60÷4?", opcoes: [12, 13, 15], resposta: 15},
  // {pergunta: "Quanto é 100÷4?", opcoes: [22, 24, 25], resposta: 25},
]
